### PR TITLE
Bump govuk template

### PR DESCRIPTION
**Pull request by tombye**
Bumps the GOVUK template and fixes the problem this brings in (see https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/338).

https://www.pivotaltracker.com/story/show/120364875

### CODE REVIEW

**Comment by pcraig3** [comment]
Noticed a couple of things:

### form fields
##### specifically, buttons and the text area get bigger in the new version

update

### footer
##### footer loses bottom padding in new version
update-2

**Comment by tombye** [comment]
@pcraig3 Good point about the `padding-bottom` problem. I've added a fix for that and rebased. 

The button changes were made to bring everyone's padding into line with elements so we should have that in. I can't see any changes to textareas in the CSS this brings in, do you think it's a problem?

**Comment by pcraig3** [comment]
New footer is flush with the sides of our columns.  Old footer wasn't.

footer

@tombye says this is better than before, and I kind of think so too.  All of our other footer links (and most of the text on the page) are left-justified to the edge of the column.

👍  from me.

**Comment by pcraig3** [comment]
Actually, there's a huge difference on firefox somehow.

Basically, all of our links not in body text seem to get smaller.

on-firefox

Not sure how we feel about this.

**Comment by pcraig3** [comment]
Worth noting that it's already made it into the buyer app, so maybe we should just suck it up.

**Pull request merged**
