### PR TITLE
Add tests for g7 content updates

### PR DESCRIPTION
**Pull request by tombye**
Tests for the page states produced by this work: https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/301

(The work was tested manually when merged, due to time constraints.)

### CODE REVIEW

**Comment by TheDoubleK** [comment]
Travis is happy - looking good to me :+1: 

(Although I'm not sure we should need the full G7 submission?  I think just having `"status": "complete"` in the dummy response should be enough to see the changes?

**Comment by tombye** [comment]
@TheDoubleK I originally had just that but was left wondering what I was testing after seeing the full G7 submission elsewhere. Felt a bit like the test could end up depending on the internals of `get_declaration_status` working in a certain way.

If we're happy the page state should always depend on the `status` property of the JSON from `data_api_client.get_selection_answers` then I'm good to change it back.

**Comment by TheDoubleK** [comment]
Put it in as it is I reckon.  All the G7-specific stuff should disappear before too long anyway.

**Comment by robyoung** [comment]
It looks like it fails when merged with master because of the change supplier declaration stuff.

**Comment by tombye** [comment]
Thanks @robyoung, fixing it now.

**Comment by TheDoubleK** [comment]
I told you to leave it alone :)

**Comment by tombye** [comment]
@TheDoubleK @robyoung Done!

**Comment by TheDoubleK** [comment]
:+1:

**Pull request merged**
