### PR TITLE
[#102069502] Assertion content update

### PR DESCRIPTION
**Pull request by TheDoubleK**
See: https://www.pivotaltracker.com/story/show/102069502

Before:
screen shot 2015-09-01 at 11 51 55

After:
screen shot 2015-09-01 at 11 51 29

### CODE REVIEW

**Comment by quis** [comment]
Roz wanted lowercase for the options:

>
You may have to provide evidence to back up your answer. Please confirm whether your response is assured by:
- independent validation
- independent testing of the implementation
- CESG-assured components
- contractual commitment
- service provider assertion

https://docs.google.com/document/d/1Cor9fKzj33Xl9v_lxwfPDcEfNytWfQFoc0BOfSuHxHU/edit

**Comment by TheDoubleK** [comment]
OK, will sort it now.

**Comment by TheDoubleK** [comment]
It will look odd though, as we have all options capitalised for the questions.

**Comment by TheDoubleK** [comment]
Lowercased for a heady mix of capitalisation all over the page:

screen shot 2015-09-01 at 12 05 00

**Comment by quis** [comment]
I think that will fail because the API is still expecting the original, capitalised form?

If so you need to set the label and value explicitly:

``` jinja
{
    'label':  'lowercase thing displayed on screen',
    'value' 'Original Thing That The API Expects'
}
```

**Comment by TheDoubleK** [comment]
Oh this gets more horrible by the minute.

**Comment by TheDoubleK** [comment]
Nice spot @quis - fixed up and tested locally - the API is happy now.

**Comment by quis** [comment]
:+1:

**Comment by TheDoubleK** [comment]
Merging this makes me sad.

**Pull request merged**
