### PR TITLE
[#98558456] Add pricing fields to draft service editing

### PR DESCRIPTION
**Pull request by robyoung**
This is a manual rebase of #134 

## Depends on
- [x] https://github.com/alphagov/digitalmarketplace-utils/pull/114
- [x] https://github.com/alphagov/digitalmarketplace-api/pull/195

### CODE REVIEW

**Comment by quis** [comment]
image

```
API POST request on http://localhost:5000/draft-services/3 failed with 400 '{'freeOption': 'answer_required', 'priceMin': 'not_a_number', 'trialOption': 'answer_required', 'vatIncluded': 'answer_required', 'educationPricing': 'answer_required'}'"
```

Have I done something wrong here? (running your branch locally)

**Comment by robyoung** [comment]
Sorry, didn't pull over the dependencies.

**Comment by TheDoubleK** [comment]
Sorry, Rob - I should have merged this first...

**Comment by TheDoubleK** [comment]
OK I've done the rebase, cos I'm good like that. Just waiting for Travis...

**Pull request merged**
