### PR TITLE
[#101660010] Extract closing date to a config variable

### PR DESCRIPTION
**Pull request by TheDoubleK**
See: https://www.pivotaltracker.com/story/show/101660010

This will ensure that the date displayed is accurate and consistent in all places it is displayed.

### CODE REVIEW

**Comment by pcraig3** [comment]
We don't care that we're losing the `<abbr>` element, do we? 
I don't really.

**Comment by TheDoubleK** [comment]
I consider it collateral damage.

**Comment by pcraig3** [comment]
Just gave Chris' pull request a thumbs-up, so you might need to refactor this soon.
But it *should* be relatively straightforward.

**Comment by pcraig3** [comment]
Actually, what do you think of doing something like incorporating the `<time>` element? 

I did it [here](https://github.com/alphagov/digitalmarketplace-supplier-frontend/commit/d47a72125c519ea241a51cbbc5c79e5b54e1be7b), but I don't think anyone else has ever done it.  I think, basically, it would call for a timestamp string and a format, both of which could be config variables.

**Comment by allait** [comment]
Can we keep the `&nbsp;`? 3pm and BST get a line break between them on the service overview page at common resolutions

**Comment by TheDoubleK** [comment]
That's why I added the <br> in front of the date - it forces the 3pm BST on to a new line, just as the &nbsp; did before.

**Comment by TheDoubleK** [comment]
Although we could put the `&nbsp;` into the time string itself - wouldn't hurt to have it everywhere the date appears rather than just on the overview page.

**Comment by TheDoubleK** [comment]
@pcraig3 - the time element is a nice idea, but feels like overkill maybe - this date isn't going to change once we go live, so why not just have the string we want to show... no need to recompute and format it every time.

**Comment by TheDoubleK** [comment]
Don't know what happened there... anyway, `&nbsp;` re-introduced and the whole lot rebased so it merges now.

**Comment by quis** [comment]
:+1:

**Pull request merged**
