### PR TITLE
Format confirmation flash message in services

### PR DESCRIPTION
**Pull request by carolinegreen**
Format confirmation flash message in services.  Replace double quotes with single quotes and change text to lowercase to match delete button at end of services pages.

Delete button:

screen shot 2015-12-01 at 17 20 07

Flash Message before:

screen shot 2015-12-01 at 17 17 30

Flash Message after:

screen shot 2015-12-01 at 17 19 01

### CODE REVIEW

**Comment by TheDoubleK** [comment]
We've agreed on no quotes at all now, and everything is updated accordingly in PR #355 (finally ready to be merged!), so this PR should be closed.

**Comment by TheDoubleK** [comment]
See this commit: https://github.com/alphagov/digitalmarketplace-supplier-frontend/commit/c46c8c40df9ef2f19daca2cdf97c31dc0ca2e574

**Comment by carolinegreen** [comment]
Oh, picked up the story on pivotal as no one was on it!  That's been the second story today, how disappointing!  Will close the pull request.

**Comment by TheDoubleK** [comment]
I know, sorry, I didn't know it had gone into Pivotal at all.

**Comment by TheDoubleK** [comment]
Sorry, I had a thought about this - on Monday afternoon discussing with @ralph-hawkins and Sarah it was decided to go with no quotes at all.  If the story in Pivotal is more recent than that then the design might have changed again and so maybe we *do* want quotes after all.

So we should check this morning to see what the final design decision is. (I don't have access to Pivotal at the moment so can't check the story right now.)

**Pull request closed without merging**
