### PR TITLE
Update bower

### PR DESCRIPTION
**Pull request by carolinegreen**

### CODE REVIEW

**Comment by pcraig3** [comment]
If you want to bring in the changes to the lab pricing (and the quality assurance stuff too), you should update the `digitalmarketplace-frameworks` to its current version while you're at it.

**Comment by quis** [comment]
Would be good to describe in the pull request what this change is bringing in, or link to the diff: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/compare/v13.1.0...v13.3.0

**Comment by carolinegreen** [comment]
I though the convention was that versions were just bumped, has this change now?

**Comment by quis** [comment]
:+1:

**Pull request merged**
