### PR TITLE
Add updates for SSP content & validation for declaration

### PR DESCRIPTION
**Pull request by tombye**
Brings in the following changes to the SSP:

1. copy changes to the hint text for the 'add a new service' journey:

https://github.com/alphagov/digitalmarketplace-ssp-content/pull/63

2. validation messages for the supplier declaration:

https://github.com/alphagov/digitalmarketplace-ssp-content/pull/53

### CODE REVIEW

**Comment by TheDoubleK** [comment]
I'm just going over the other SSP content PR now to check question numbers reconcile properly.

Fine to merge this now if you like, but was planning to get all pending changes in before bumping the content.

**Comment by tombye** [comment]
@TheDoubleK makes sense to do them in order.

**Comment by robyoung** [comment]
Does that mean we should close this PR and wait for one that encompasses all changes?

**Comment by tombye** [comment]
Yeah, I'll do that until the numbers in the validation match the content. Once we're at that point I'm happy to rewrite this one to encompass those other changes.

**Comment by TheDoubleK** [comment]
Aargh, sorry Tom, this update has gone in now with a different PR.

**Comment by tombye** [comment]
@TheDoubleK If you point to it I'm happy to redo this one to remove those changes.

**Comment by TheDoubleK** [comment]
https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/205

This one just needs to be closed I think as it's the same change. (Don't think you had re-opened this one yet when I made that one).

**Pull request closed without merging**
