### PR TITLE
removes hanging bullets and adds secondary bullet style

### PR DESCRIPTION
**Pull request by ralph-hawkins**
Everyone hates hanging bullets, so I removed them. Adds a secondary bullet style to make nested lists clearer.

Looks like this:
screen shot 2017-02-28 at 14 19 03

### CODE REVIEW

**Comment by samuelhwilliams** [comment]
Is this something that can/should be done across the whole app rather than just the supplier declaration? Feels like a pattern we would probably want to use everywhere as opposed to just this page. If that is the case, we should probably do equivalent PRs for buyer and admin frontends until we have a way to unify resources like this.

**Comment by samuelhwilliams** [comment]
Would this make more sense to do in dm-frontend-toolkit so that it's consistent across all pages on all apps? Feels like a pattern we might want to use as standard rather than just on the supplier declaration.

**Comment by samuelhwilliams** [comment]
But for now, 👍

**Comment by ralph-hawkins** [comment]
@pcraig3 do you have an opinion on putting this in the toolkit, does the declaration use the same styles?

@superroz how much we want to encourage nested lists?

**Comment by TheDoubleK** [comment]
There are already toolkit styles for lists - can we just use them?
http://alphagov.github.io/digitalmarketplace-frontend-toolkit/shared_scss/lists.html

**Comment by TheDoubleK** [comment]
Oh, sorry - they maybe don't have nested lists.  But if we're using nested lists maybe those styles should live there in the toolkit.

**Comment by ralph-hawkins** [comment]
Spoke to @superroz and we don't use nested bullets anywhere and we don't want to. They are something that we'd like to contained to the declaration. So I'm going to add them here and not in the toolkit.

**Comment by samuelhwilliams** [comment]
We don't want this pattern to spread without people having to justify it, so will merge it to here rather than the general frontend-toolkit.

**Pull request merged**
