### PR TITLE
Allow the JavaScript tests to run in CI

### PR DESCRIPTION
**Pull request by tombye**
You can currently only run the JavaScript tests by loading the test runner in a browser.

This adds a Gulp task which uses PhantomJS to run the tests so it can be done from a command as well.

Travis apparently has PhantomJS as part of its environment: http://docs.travis-ci.com/user/ci-environment/#Headless-Browser-Testing-Tools

### Notes

There were a few problems getting the plugin to work with Travis, the details of which (and the reason we're pointing to a Github repo in the `package.json`) is explained here:

http://stackoverflow.com/questions/32461456/travis-ci-can-the-version-of-node-installed-on-all-vm-images-match-the-latest

and here:

https://github.com/alphagov/gulp-jasmine-phantom/pull/1

### CODE REVIEW

**Comment by tombye** [comment]
Closing this until I can work out how to set Node to 0.12.x in travis (if at all).

**Comment by quis** [comment]
I think you need to add a line to `./scripts/run_tests.sh` to actually make them them run on Travis. I can't see any Jasmine output [here](https://travis-ci.org/alphagov/digitalmarketplace-supplier-frontend/jobs/79316891).

**Comment by tombye** [comment]
@quis good point! I plugged it in in 5ae5a8e so should be done now.

**Comment by tombye** [comment]
OK, I've altered `scripts/run_tests.sh` to better follow the convention and to make it explicit which tests have passed/failed.

**Comment by quis** [comment]
:+1:

**Pull request merged**
