### PR TITLE
Explain 'BST' where used in the G7 deadline

### PR DESCRIPTION
**Pull request by tombye**
As pointed out by @pcraig3 in https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/246#issuecomment-136648789

### CODE REVIEW

**Comment by minglis** [comment]
👍

**Comment by TheDoubleK** [comment]
The `<abbr>` that got removed previously was "British Standard Time" rather than "British Summer Time".  I have no opinion on which is correct - just saying this is different from how it was.

**Comment by TheDoubleK** [comment]
Either way I do think all three words should be capitalised though - it is a proper name for the time zone.

**Comment by tombye** [comment]
@TheDoubleK I think this deals with the other instance of that capitalisation problem: https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/247#issuecomment-136662723

**Comment by TheDoubleK** [comment]
:+1:

**Pull request merged**
