### PR TITLE
Show services and documents links on dashboard

### PR DESCRIPTION
**Pull request by domoscargin**
https://trello.com/c/ZUgsBovZ/361-2-prep-and-test-buying-journey-for-g12-on-preview

When a framework is live, we want users to be able to view their services and documents, even if they have an agreement signature outstanding.

### CODE REVIEW

**Review by lfdebrux — APPROVED** [review]
Looks good to me.

**Review by lfdebrux — CHANGES_REQUESTED** [review]
Could we have it that they have the sign framework agreement link even if they're suspended?

**Comment by domoscargin** [comment]
So this now fails [`test_opportunities_dashboard_link_fails_with_incomplete_data`](https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/8e82a0f300d5b80c881aeb9bdd3389f66a06e544/tests/app/main/test_suppliers.py#L1120-L1134), since this logic doesn't use the `onFramework` property. The "view services/documents" links all appear on this test.

I'm not entirely sure I've copied the logic correctly, and I'm not entirely sure what should be showing in this test case now - the copied logic seems to bypass `onFramework` and `services_count`, but are there specific cases that should happen?

**Comment by lfdebrux** [comment]
I've pushed some changes to try and fix the tests.

**Review by lfdebrux — APPROVED** [review]

**Pull request merged**
