### PR TITLE
Deny third-party sites from embedding in an iframe

### PR DESCRIPTION
**Pull request by pcraig3**
Upgrading to new verison of dmutils which initiates each app with the `X-Frame-Options` header set to `DENY`.
Also added test to confirm.

### CODE REVIEW

**Comment by quis** [comment]
Same comment as on the buyer's app, testing for the header would be better (I think) as its own separate test.

**Comment by quis** [comment]
Also, good branch name.

**Comment by minglis** [comment]
As per Chris comment, would the test fit in here?

https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/master/tests/app/test_application.py

**Comment by pcraig3** [comment]
@minglis Sure, it's an app-wide setting, so seems logical.

@quis Branch name's a bit of a stretch, but I got there in the end.

**Pull request merged**
