### PR TITLE
Use mypy to test typing

### PR DESCRIPTION
**Pull request by bjgill**
This PR adds [`mypy`](http://mypy-lang.org/) static type checking to the checks performed on `make test` and on Travis CI (but not on commit).

I've also fixed/ignored the issues mypy picked up as appropriate.

I copied the approach from [dmrunner](https://github.com/alphagov/digitalmarketplace-runner/pull/51), which we did first.

### CODE REVIEW

**Review by lfdebrux — APPROVED** [review]
Nice!

**Comment by bjgill** [comment]
Oh dear. We've hit https://github.com/python/mypy/issues/9656.

**Comment by lfdebrux** [comment]
> Oh dear. We've hit [python/mypy#9656](https://github.com/python/mypy/issues/9656).

Maybe we should just pin to the older version of mypy and hope they find a way around this issue?

**Comment by bjgill** [comment]
Agreed. There is a workaround (assign the lambda to a variable), but it's a bit silly.

**Pull request merged**
