### PR TITLE
258 update questions in frameworks repo 2

### PR DESCRIPTION
**Pull request by benvand**
https://trello.com/c/EoMme9Md/258-update-questions-in-frameworks-repo-2

See commits

#### Depends on:
https://github.com/alphagov/digitalmarketplace-frameworks/pull/605/files

screencapture-localhost-suppliers-frameworks-g-cloud-12-declaration-edit-providing-suitable-services-2020-02-11-08_26_45

### CODE REVIEW

**Comment by lfdebrux** [comment]
Hmm, I think I agree with @risicle on this one, if we're doing validation at the time of the declaration then these questions are at best redundant and at worst confusing and contradictory.

If we are able to I think we should instead ask these questions about each and every service submitted.

**Comment by risicle** [comment]
Of course, something being the right way to do something and us actually agreeing it with our wonderful partners and making the technical changes required for it in time are two different things...

**Comment by benvand** [comment]
@risicle @lfdebrux 
This is out of scope of this PR.

The 'declaration' journey step needs a rethink form the ground up.

**Comment by benvand** [comment]
Sorry, that sounds like a snap, it's not, it's just me and @katstevens both raised this when the ask came in and got nowhere.

**Comment by lfdebrux** [comment]
> Sorry, that sounds like a snap, it's not, it's just me and @katstevens both raised this when the ask came in and got nowhere.

Understood

**Pull request merged**
