### PR TITLE
[#112216509] Only eligible suppliers can respond to a brief

### PR DESCRIPTION
**Pull request by pcraig3**
This pull request throws up an error page if you try to apply for or submit a clarification question for an opportunity that you're not eligible for.  Error pages will tell you what you can't do and if (a) you're not on the framework, or (b) you don't provide the right service.  Hard to be more helpful than that without getting into DOS-specific messaging, which we don't want to do.

@superroz, @ralph-hawkins, and, most recently, @suedavis have all looked at it.

*** 
### Trying to apply, not on the framework
screen shot 2016-03-30 at 11 29 16

### Trying to apply, don't provide the right services
screen shot 2016-03-30 at 11 32 26

### Trying to submit a clarification question, not on the framework
screen shot 2016-03-30 at 11 31 46

### Trying to submit a clarification question, don't provide the right services
screen shot 2016-03-30 at 11 32 45

### CODE REVIEW

**Comment by ralph-hawkins** [comment]
:+1: nice apostrophes :-)

**Comment by superroz** [comment]
Can we replace 'therefore' with 'so’?

**Comment by pcraig3** [comment]
Updated with new words.

**Comment by superroz** [comment]
:+1:

**Pull request merged**
