### PR TITLE
Closely pack "Become a supplier" paragraphs

### PR DESCRIPTION
**Pull request by TheDoubleK**
Pulls in new content from:
 - [x] https://github.com/alphagov/digitalmarketplace-frameworks/pull/471

## All closed
screen shot 2017-09-19 at 12 29 09

## All Open/Coming
screen shot 2017-09-19 at 12 29 43

## One of each
screen shot 2017-09-19 at 12 14 20

### CODE REVIEW

**Comment by samuelhwilliams** [comment]
I don't think we quote framework names anywhere else, do we? What's the justification for doing it here?

**Comment by idavidmcdonald** [comment]
The content also looks a bit squished together?

**Comment by samuelhwilliams** [comment]
And the links aren't very strongly associated to their 'parents'; could do with the top margin/border being smaller. :trollface:

**Comment by TheDoubleK** [comment]
I've sat with Laurence this morning sorting this out.  He wants it squished together - the problem this fixes is that the content is too spread out.  As for quoting framework names, ¯\\_(ツ)_/¯

**Comment by idavidmcdonald** [comment]
Also should what you can sell for g cloud be:

cloud hosting
cloud software
cloud support

As they are the lot names, at the moment we have something different (ambiguity over things not being cloud and the word technical now added)

**Comment by TheDoubleK** [comment]
Current screenshots, for comparison, are here: 
https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/741

**Comment by TheDoubleK** [comment]
Those words came from Karl, there was some discussion of them on the previous PR I think ¯\\(ツ)/¯

**Comment by TheDoubleK** [comment]
This PR is specifically about spacing.

If we want to change the words that will be a new story.

**Comment by TheDoubleK** [comment]
I'm going to hold off merging this as lots of people don't like it...

**Comment by TheDoubleK** [comment]
@samuelhwilliams > "And the links aren't very strongly associated to their 'parents'"

@laurenceberry says the links aren't associated to a particular framework, so in the case of "both open" or "both closed" the link doesn't need to seem like it's only associated with the final framework listed on the page.

In the "one of each" case it is maybe a bit more room than we'd like, but maybe we live with that because it means we can use the link style straight out of the toolkit rather than create yet another variation.

**Comment by samuelhwilliams** [comment]
My issue is primarily with the 'one of each' page. On the other two versions the link looks OK (i.e. when there's nothing after it with equal spacing).

Re: parents, I meant the heading/section rather than the framework. I understand that at some indeterminate point in the future we'll have more than two frameworks and in that case we don't want the link to stick to the final one.

**Comment by TheDoubleK** [comment]
@samuelhwilliams the content community says the quotes should go.   You can make it happen by adding your thumb here: https://github.com/alphagov/digitalmarketplace-frameworks/pull/472

**Comment by TheDoubleK** [comment]
Laurence has double-checked over this and he's happy so going to merge it.

**Pull request merged**
