### PR TITLE
Update Registered Address - Country field

### PR DESCRIPTION
**Pull request by domoscargin**
This PR does two things:

1. Replaces our hardcoded `<select>` with a `govukSelect` component.
2. Bumps govuk-country-and-territory-autocomplete

We previously avoided bumping from 0.5.0 because our functional tests failed: #1355 

However, we can fix this by using an updated test: alphagov/digitalmarketplace-functional-tests#622

This does not address the potential issues with the underlying autocomplete: alphagov/accessible-autocomplete#472

### CODE REVIEW

**Comment by lfdebrux** [comment]
> However, we can fix this by using an updated test: alphagov/digitalmarketplace-functional-tests#622

Ah, I forgot we had a step specifically for the autocomplete, good spot!

https://github.com/alphagov/digitalmarketplace-functional-tests/blob/master/features/admin/company_details_edit.feature#L66

https://github.com/alphagov/digitalmarketplace-functional-tests/blob/0e8beed2264e854b631efd1e55a4e85e47d13732/features/step_definitions/common_steps.rb#L236

**Comment by lfdebrux** [comment]
I'm getting a JavaScript error on the supplier company details page

```
Uncaught TypeError: Cannot read property 'options' of null
    at o (picker-engine.min.js:formatted:5313)
    at CountryAutocomplete (app-location-autocomplete.js:7)
    at app-location-autocomplete.js:20
    at app-location-autocomplete.js:21
```

**Comment by domoscargin** [comment]
> I'm getting a JavaScript error on the supplier company details page
> 
> ```
> Uncaught TypeError: Cannot read property 'options' of null
>     at o (picker-engine.min.js:formatted:5313)
>     at CountryAutocomplete (app-location-autocomplete.js:7)
>     at app-location-autocomplete.js:20
>     at app-location-autocomplete.js:21
> ```

Hmm, can't replicate. Is this just on first page load?

**Comment by lfdebrux** [comment]
Hmm, I can't replicate it either now; must have been something on my machine.

**Review by lfdebrux — APPROVED** [review]
Uses Design System component, removes JavaScript, updates dependencies... it's :chef-kiss:

**Comment by lfdebrux** [comment]
This will require functional test changes, I've made a PR.

https://github.com/alphagov/digitalmarketplace-functional-tests/pull/865

**Pull request merged**
