### PR TITLE
Make it clear that this is the MIT licence

### PR DESCRIPTION
**Pull request by annashipman**
I was looking for a licence to send someone as an example and noticed that this one doesn't make it clear it's the MIT licence. This PR changes that, to make it easier for people to understand what licence is being used.

### CODE REVIEW

**Comment by annashipman** [comment]
As per, for example, https://github.com/alphagov/digitalmarketplace-aws/blob/master/LICENSE

**Comment by allait** [comment]
Good call, thanks @annashipman!

We'll add them to some other ones that are missing. This also made me realise that between our repos we have 3 LICENSE files and 8 LICENCE files. We should probably choose one.

**Comment by TheDoubleK** [comment]
I vote "LICENCE"!

**Comment by allait** [comment]
Github search shows LICENSE is 20 times more popular though.

**Comment by TheDoubleK** [comment]
Really?
¯\_(ツ)_/¯

**Comment by annashipman** [comment]
LICENCE is the British spelling; LICENSE is the American spelling. So I also vote LICENCE.

...for the filename. However, for the licence itself, I'd use the exact wording, so `The MIT License` https://opensource.org/licenses/MIT

**Pull request merged**
